"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GameType = void 0;
var GameType;
(function (GameType) {
    GameType[GameType["QUAKECRAFT"] = 2] = "QUAKECRAFT";
    GameType[GameType["WALLS"] = 3] = "WALLS";
    GameType[GameType["PAINTBALL"] = 4] = "PAINTBALL";
    GameType[GameType["SURVIVAL_GAMES"] = 5] = "SURVIVAL_GAMES";
    GameType[GameType["TNTGAMES"] = 6] = "TNTGAMES";
    GameType[GameType["VAMPIREZ"] = 7] = "VAMPIREZ";
    GameType[GameType["WALLS3"] = 13] = "WALLS3";
    GameType[GameType["ARCADE"] = 14] = "ARCADE";
    GameType[GameType["ARENA"] = 17] = "ARENA";
    GameType[GameType["UHC"] = 20] = "UHC";
    GameType[GameType["MCGO"] = 21] = "MCGO";
    GameType[GameType["BATTLEGROUND"] = 23] = "BATTLEGROUND";
    GameType[GameType["SUPER_SMASH"] = 24] = "SUPER_SMASH";
    GameType[GameType["GINGEBREAD"] = 25] = "GINGEBREAD";
    GameType[GameType["HOUSING"] = 26] = "HOUSING";
    GameType[GameType["SKYWARS"] = 51] = "SKYWARS";
    GameType[GameType["TRUE_COMBAT"] = 52] = "TRUE_COMBAT";
    GameType[GameType["SPEED_UHC"] = 54] = "SPEED_UHC";
    GameType[GameType["SKYCLASH"] = 55] = "SKYCLASH";
    GameType[GameType["LEGACY"] = 56] = "LEGACY";
    GameType[GameType["PROTOTYPE"] = 57] = "PROTOTYPE";
    GameType[GameType["BEDWARS"] = 58] = "BEDWARS";
    GameType[GameType["MURDER_MYSTERY"] = 59] = "MURDER_MYSTERY";
    GameType[GameType["BUILD_BATTLE"] = 60] = "BUILD_BATTLE";
    GameType[GameType["DUELS"] = 61] = "DUELS";
    GameType[GameType["SKYBLOCK"] = 63] = "SKYBLOCK";
    GameType[GameType["PIT"] = 64] = "PIT";
})(GameType = exports.GameType || (exports.GameType = {}));
